
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */

import java.sql.*;
import javax.swing.JOptionPane;
import mypack.*;
public class AdminHome extends javax.swing.JFrame {

    /**
     * Creates new form AdminHome
     */
    private String unm,pass,role2,fnm="",lnm="";
    public AdminHome() {
        initComponents();
        
           Toolkit tk= Toolkit.getDefaultToolkit();
           Dimension d= tk.getScreenSize();
           this.setBounds(0,0, d.width, d.height);
           
           Image i=Toolkit.getDefaultToolkit().getImage(getClass().getResource("\\images\\abstract-pastel-blue-white-background-design-34948659.jpg"));
           Dimension dim=Toolkit.getDefaultToolkit().getScreenSize();
       
        Image j=i.getScaledInstance(dim.width, dim.height, Image.SCALE_REPLICATE);
        ImageIcon img=new ImageIcon(j);
        jLabel5.setIcon(img);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        unmtxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pwd = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        btnlogin = new javax.swing.JButton();
        btnclr = new javax.swing.JButton();
        btnforgot = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        jPanel1.setLayout(null);

        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 561, 443);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        jLabel1.setText("Username");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 80, 80, 30);

        unmtxt.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        jPanel1.add(unmtxt);
        unmtxt.setBounds(180, 80, 160, 30);

        jLabel2.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        jLabel2.setText("Password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 150, 80, 16);

        pwd.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        jPanel1.add(pwd);
        pwd.setBounds(180, 140, 160, 30);

        jLabel3.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        jLabel3.setText("Role");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 200, 70, 20);

        jRadioButton1.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        jRadioButton1.setText("Admin");
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(120, 200, 80, 25);

        jRadioButton2.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        jRadioButton2.setText("Teacher");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(210, 200, 90, 25);

        jRadioButton3.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        jRadioButton3.setText("Student");
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(310, 200, 90, 25);

        btnlogin.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        btnlogin.setText("Login");
        jPanel1.add(btnlogin);
        btnlogin.setBounds(190, 330, 100, 30);

        btnclr.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        btnclr.setText("Clear");
        jPanel1.add(btnclr);
        btnclr.setBounds(310, 330, 80, 30);

        btnforgot.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        btnforgot.setText("Forgot Password");
        jPanel1.add(btnforgot);
        btnforgot.setBounds(20, 330, 150, 30);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclr;
    private javax.swing.JButton btnforgot;
    private javax.swing.JButton btnlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JPasswordField pwd;
    private javax.swing.JTextField unmtxt;
    // End of variables declaration//GEN-END:variables
}
