


import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import mypack.connect_me;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.*;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class DisplayMenu extends javax.swing.JFrame {

    /**
     * Creates new form DisplayMenu
     */
     String stream,sub,streamId="s",username="",firstname="",lastname="";
     int sem,subId;
     Dimension d;
    public DisplayMenu() {
        initComponents();
           connect_me.connect_all();
           
       
    }
    public DisplayMenu(String unm,String firstnm,String lastnm)
    {
        initComponents();
        connect_me.connect_all();
        
          
        username=unm;
        firstname=firstnm;
        lastname=lastnm;
         
        if(connect_me.role.equalsIgnoreCase("teacher"))
        {
            jMenu2.setVisible(false);
            regTeacher.setVisible(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        pd = new javax.swing.JMenuItem();
        sd = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        regTeacher = new javax.swing.JMenuItem();
        chngpwd = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        addsub = new javax.swing.JMenuItem();
        delsub = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        addq = new javax.swing.JMenuItem();
        delq = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        format = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setForeground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setText("Home");
        jMenu1.setFont(new java.awt.Font("Modern No. 20", 1, 18)); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        pd.setText("Personal Details");
        pd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdActionPerformed(evt);
            }
        });
        jMenu1.add(pd);

        sd.setText("Subject Details");
        sd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdActionPerformed(evt);
            }
        });
        jMenu1.add(sd);
        jMenu1.add(jSeparator1);

        regTeacher.setText("Register Teacher");
        regTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regTeacherActionPerformed(evt);
            }
        });
        jMenu1.add(regTeacher);

        chngpwd.setText("Change Password");
        chngpwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chngpwdActionPerformed(evt);
            }
        });
        jMenu1.add(chngpwd);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Subjects");
        jMenu2.setFont(new java.awt.Font("Modern No. 20", 1, 18)); // NOI18N

        addsub.setText("Add Subject");
        addsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addsubActionPerformed(evt);
            }
        });
        jMenu2.add(addsub);

        delsub.setText("Delete Subject");
        delsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delsubActionPerformed(evt);
            }
        });
        jMenu2.add(delsub);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Questions");
        jMenu3.setFont(new java.awt.Font("Modern No. 20", 1, 18)); // NOI18N

        addq.setText("Add Questions");
        addq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addqActionPerformed(evt);
            }
        });
        jMenu3.add(addq);

        delq.setText("Delete Questions");
        delq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delqActionPerformed(evt);
            }
        });
        jMenu3.add(delq);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Paper");
        jMenu4.setFont(new java.awt.Font("Modern No. 20", 1, 18)); // NOI18N
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        format.setFont(new java.awt.Font("Modern No. 20", 0, 14)); // NOI18N
        format.setText("Define Format");
        format.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formatActionPerformed(evt);
            }
        });
        jMenu4.add(format);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1023, 742));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addsubActionPerformed
        // TODO add your handling code here:
        JInternalFrame []x= jDesktopPane1.getAllFrames();
        for(int i=0;i<x.length; i++)
        {
            x[i].dispose();
        }
        //d=jDesktopPane1.getSize();
        Subjects_frame s=new Subjects_frame();
        //s.setSize(d);
       // s.setPreferredSize(d);
       // s.setBounds(0,0,s.getWidth(),s.getHeight());
        jDesktopPane1.add(s);
        s.deltab.setSelectedIndex(0);
        
        
    }//GEN-LAST:event_addsubActionPerformed

    private void delsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delsubActionPerformed
        // TODO add your handling code here:
        JInternalFrame []x= jDesktopPane1.getAllFrames();
        for(int i=0;i<x.length; i++)
        {
            x[i].dispose();
        }
        //d=jDesktopPane1.getSize();
        Subjects_frame s=new Subjects_frame();
        //s.setSize(d);
        //s.setPreferredSize(d);
       // s.setBounds(0,0,s.getWidth(),s.getHeight());
        jDesktopPane1.add(s);
        s.deltab.setSelectedIndex(1);
    }//GEN-LAST:event_delsubActionPerformed

    private void addqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addqActionPerformed
        // TODO add your handling code here:
         JInternalFrame []x= jDesktopPane1.getAllFrames();
        for(int i=0;i<x.length; i++)
        {
            x[i].dispose();
        }
        //d=jDesktopPane1.getSize();
        FrmQuestions q=new FrmQuestions(username);
        //q.setSize(d);
        //q.setPreferredSize(d);
       // q.setBounds(0,0,q.getWidth(),q.getHeight());
        jDesktopPane1.add(q);
        q.addel.setSelectedIndex(0);
    }//GEN-LAST:event_addqActionPerformed

    private void delqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delqActionPerformed
        // TODO add your handling code here:
           JInternalFrame []x= jDesktopPane1.getAllFrames();
        for(int i=0;i<x.length; i++)
        {
            x[i].dispose();
        }
        //d=jDesktopPane1.getSize();
        FrmQuestions q=new FrmQuestions(username);
        //q.setSize(d);
        //q.setPreferredSize(d);
        //q.setBounds(0,0,q.getWidth(),q.getHeight());
        jDesktopPane1.add(q);
        q.addel.setSelectedIndex(1);
    }//GEN-LAST:event_delqActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
      
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void sdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdActionPerformed
        // TODO add your handling code here:
        JInternalFrame []x= jDesktopPane1.getAllFrames();
        for(int i=0;i<x.length; i++)
        {
            x[i].dispose();
        }
        //d=jDesktopPane1.getSize();
        FrmTeacherUpdate f= new FrmTeacherUpdate(username);
        //f.setSize(d);
        //f.setPreferredSize(d);
       // f.setBounds(0,0,f.getWidth(),f.getHeight());
        jDesktopPane1.add(f);
        f.UpdateTab.setSelectedIndex(1);
    }//GEN-LAST:event_sdActionPerformed

    private void pdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdActionPerformed
        // TODO add your handling code here:
        JInternalFrame []x= jDesktopPane1.getAllFrames();
        for(int i=0;i<x.length; i++)
        {
            x[i].dispose();
        }
       // d=jDesktopPane1.getSize();
        FrmTeacherUpdate f= new FrmTeacherUpdate(username);
       // f.setSize(d);
        //f.setPreferredSize(d);
        //f.setBounds(0,0,f.getWidth(),f.getHeight());
        jDesktopPane1.add(f);
        //f.show();
        f.UpdateTab.setSelectedIndex(0);

        // f1.grabFocus();

    }//GEN-LAST:event_pdActionPerformed

    private void formatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formatActionPerformed
        // TODO add your handling code here:
        JInternalFrame []x= jDesktopPane1.getAllFrames();
        for(int i=0;i<x.length; i++)
        {
            x[i].dispose();
        }
       // d=jDesktopPane1.getSize();
        FrmExamType f=new FrmExamType(username);
        //f.setSize(d);
       // f.setPreferredSize(d);
       // f.setBounds(0,0,f.getWidth(),f.getHeight());
        jDesktopPane1.add(f);

    }//GEN-LAST:event_formatActionPerformed

    private void chngpwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chngpwdActionPerformed
        // TODO add your handling code here:
          JInternalFrame []x= jDesktopPane1.getAllFrames();
        for(int i=0;i<x.length; i++)
        {
            x[i].dispose();
        }
        //d=jDesktopPane1.getSize();
        FrmChangePwd p=new FrmChangePwd(username);
        //p.setSize(d);
        //p.setPreferredSize(d);
        //p.setBounds(0,0,p.getWidth(),p.getHeight());
        jDesktopPane1.add(p);
    }//GEN-LAST:event_chngpwdActionPerformed

    private void regTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regTeacherActionPerformed
        // TODO add your handling code here:
        JInternalFrame []x= jDesktopPane1.getAllFrames();
        for(int i=0;i<x.length; i++)
        {
            x[i].dispose();
        }
        //d=jDesktopPane1.getSize();
        TeacherDetailsFrame tr=new TeacherDetailsFrame(username);
        //tr.setSize(d);
        //tr.setPreferredSize(d);
       // tr.setBounds(0,0,tr.getWidth(),tr.getHeight());
        jDesktopPane1.add(tr);
    }//GEN-LAST:event_regTeacherActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayMenu().setVisible(true);
              
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addq;
    private javax.swing.JMenuItem addsub;
    private javax.swing.JMenuItem chngpwd;
    private javax.swing.JMenuItem delq;
    private javax.swing.JMenuItem delsub;
    private javax.swing.JMenuItem format;
    public static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem pd;
    private javax.swing.JMenuItem regTeacher;
    private javax.swing.JMenuItem sd;
    // End of variables declaration//GEN-END:variables
}
