/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */

import java.sql.*;
import javax.swing.JOptionPane;
import mypack.*;

public class Register extends javax.swing.JFrame {
    
    private String unm,pass,repass,secQ,secA;

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        connect_me.connect_all();
        try
        {
            connect_me.st=connect_me.con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            String sql="select userid from login";
            connect_me.rs=connect_me.st.executeQuery(sql);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e.toString());
        }
        err.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        unmtxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        pwd = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        repwd = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        securityQ = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        ans = new javax.swing.JTextField();
        reg = new javax.swing.JButton();
        btnClr = new javax.swing.JButton();
        err = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        jLabel2.setText("Username");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 70, 90, 30);

        unmtxt.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        unmtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unmtxtActionPerformed(evt);
            }
        });
        unmtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                unmtxtFocusLost(evt);
            }
        });
        unmtxt.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                unmtxtInputMethodTextChanged(evt);
            }
        });
        jPanel1.add(unmtxt);
        unmtxt.setBounds(200, 70, 150, 30);

        jLabel1.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        jLabel1.setText("Password");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 130, 60, 20);

        pwd.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        pwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdActionPerformed(evt);
            }
        });
        jPanel1.add(pwd);
        pwd.setBounds(200, 120, 150, 30);

        jLabel3.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        jLabel3.setText("Re-enter password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 170, 130, 30);

        repwd.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        jPanel1.add(repwd);
        repwd.setBounds(200, 170, 150, 30);

        jLabel4.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        jLabel4.setText("Security question");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 210, 120, 30);

        securityQ.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        securityQ.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select question", "What is your hobby?", "What is your favourite serial?", "What is your first name?", "Who is your favourite sportsman?" }));
        securityQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                securityQActionPerformed(evt);
            }
        });
        jPanel1.add(securityQ);
        securityQ.setBounds(200, 210, 250, 40);

        jLabel5.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        jLabel5.setText("Answer");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 270, 90, 30);

        ans.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        jPanel1.add(ans);
        ans.setBounds(200, 260, 150, 30);

        reg.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        reg.setText("Register");
        reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regActionPerformed(evt);
            }
        });
        jPanel1.add(reg);
        reg.setBounds(250, 360, 170, 40);

        btnClr.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        btnClr.setText("Clear");
        btnClr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClrActionPerformed(evt);
            }
        });
        jPanel1.add(btnClr);
        btnClr.setBounds(100, 360, 140, 40);

        err.setFont(new java.awt.Font("Modern No. 20", 2, 12)); // NOI18N
        err.setForeground(new java.awt.Color(255, 0, 0));
        err.setText("jLabel6");
        jPanel1.add(err);
        err.setBounds(350, 80, 160, 13);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 510, 480);

        setSize(new java.awt.Dimension(516, 515));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public int check(String unm)
    {
        try
        {
            connect_me.st1=connect_me.con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            String sql="select userid from login";
            connect_me.rs1=connect_me.st1.executeQuery(sql);
            
            while(connect_me.rs1.next())
            {
                if(unm.equalsIgnoreCase(connect_me.rs1.getString(1)))
                {
                    JOptionPane.showMessageDialog(rootPane, "Enter different Username");
                    unmtxt.grabFocus();
                    break;
                    
                    //connect_me.st1.close();
                }
            }
            if(connect_me.rs1.next())
            {
                return 0;
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Proceed with the registration");
                return 1;
            }
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e.toString());
            return 0;
        }
    }
    
    
    private void securityQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_securityQActionPerformed
        // TODO add your handling code here:
        secQ=securityQ.getSelectedItem().toString();
        if(secQ.equals("select question"))
        {
            JOptionPane.showMessageDialog(rootPane, "Select a question");
        }
        
    }//GEN-LAST:event_securityQActionPerformed

    private void regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regActionPerformed
        // TODO add your handling code here:
        try
        {
          
        
             connect_me.st1=connect_me.con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            String sql="select userid from login";
            connect_me.rs1=connect_me.st1.executeQuery(sql);
            
           
        
        
            
            unm=unmtxt.getText();
            pass=pwd.getText();
            repass=repwd.getText();
            secA=ans.getText();
            if(unm.equals(""))
            {
                JOptionPane.showMessageDialog(rootPane, "Enter Username");
                unmtxt.grabFocus();
                return;
            }
            if(pass.equals(""))
            {
                JOptionPane.showMessageDialog(rootPane, "Enter Password");
                pwd.grabFocus();
                return;
            }
            if(repass.equals(""))
            {
                JOptionPane.showMessageDialog(rootPane, "Password missing");
                repwd.grabFocus();
                return;
            }
            if(secA.equals(""))
            {
                JOptionPane.showMessageDialog(rootPane, "Enter answer to security question");
                ans.grabFocus();
                return;
            }
            
            while(connect_me.rs1.next())
            {
                if(unm.equalsIgnoreCase(connect_me.rs1.getString(1)))
                {
                    JOptionPane.showMessageDialog(rootPane, "Enter different Username");
                    unmtxt.grabFocus();
                    
                    
                    //connect_me.st1.close();
                }
            }
            
            //int i=check(unm);
            
            //if(i==1)
            //{
                if(pass.equals(repass))
            {
                 connect_me.st=connect_me.con.createStatement();
                 String sql1="insert into login values('"+unm+"','"+pass+"','"+secQ+"','"+secA+"','')";
                 connect_me.st.executeUpdate(sql1);
                 JOptionPane.showMessageDialog(rootPane, unm + " you are registered successfully");
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Passwords do not match");
            }
            //}
            
            
            
            
            
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e.toString());
        }
    }//GEN-LAST:event_regActionPerformed

    private void btnClrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClrActionPerformed
        // TODO add your handling code here:
        int i=JOptionPane.showConfirmDialog(rootPane, "Do you really want to clear?");
        if(i==0)
        {
            unmtxt.setText("");
            pwd.setText("");
            repwd.setText("");
            ans.setText("");
        }
    }//GEN-LAST:event_btnClrActionPerformed

    private void pwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_pwdActionPerformed

    private void unmtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unmtxtActionPerformed
        // TODO add your handling code here:
        
        
       /* try
        {
             connect_me.st=connect_me.con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            String sql="select userid from login";
            connect_me.rs=connect_me.st.executeQuery(sql);
            
            
            while(connect_me.rs.next())
            {
                if(unm.equals(connect_me.rs.getString(1)))
                {
                    JOptionPane.showMessageDialog(rootPane, "Enter different username");
                }
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e.toString());
        }
        
        */
    }//GEN-LAST:event_unmtxtActionPerformed

    private void unmtxtInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_unmtxtInputMethodTextChanged
        // TODO add your handling code here:
        
            
        
        
    }//GEN-LAST:event_unmtxtInputMethodTextChanged

    private void unmtxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_unmtxtFocusLost
        // TODO add your handling code here:
        unm=unmtxt.getText();
        if(unm.equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Enter Username");
            unmtxt.grabFocus();
            return;
        }
         try
        {
             connect_me.st=connect_me.con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            String sql="select userid from login";
            connect_me.rs=connect_me.st.executeQuery(sql);
            boolean flag=true;
            //unm=unmtxt.getText();
            while(connect_me.rs.next())
            {
                if(unm.equals(connect_me.rs.getString(1)))
                {
                    err.setVisible(true);
                    err.setText("Enter different username");
                    //JOptionPane.showMessageDialog(rootPane, "Enter different username");
                    
                            
                    flag=false;
                    break;
                    
                    
                }
                
            }
            if(flag==true)
            {
                JOptionPane.showMessageDialog(rootPane, "Proceed with the registration");
                err.setVisible(false);
            }
            else
            {
                unmtxt.setText("");
                unmtxt.grabFocus();
            }
            
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e.toString());
        }
        
    }//GEN-LAST:event_unmtxtFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ans;
    private javax.swing.JButton btnClr;
    private javax.swing.JLabel err;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pwd;
    private javax.swing.JButton reg;
    private javax.swing.JPasswordField repwd;
    private javax.swing.JComboBox securityQ;
    private javax.swing.JTextField unmtxt;
    // End of variables declaration//GEN-END:variables
}
