
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
//package newpackage;

/**
 *
 * @author Administrator
 */
public class TestInternal extends javax.swing.JInternalFrame {

    /**
     * Creates new form TestInternal
     */
    public TestInternal() {
        initComponents();
        Image im=Toolkit.getDefaultToolkit().getImage(getClass().getResource("\\images\\abstract-pastel-blue-white-background-design-34948659.jpg"));
            //Dimension dim=Toolkit.getDefaultToolkit().getScreenSize();
       
            Image j=im.getScaledInstance(this.getWidth(), this.getHeight(), Image.SCALE_REPLICATE);
            ImageIcon img=new ImageIcon(j);
            jLabel2.setIcon(img);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Format");
        setOpaque(true);
        setVisible(true);
        addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                formVetoableChange(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 344, 350);
    }// </editor-fold>//GEN-END:initComponents

    private void formVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_formVetoableChange
        // TODO add your handling code here:
        Image im=Toolkit.getDefaultToolkit().getImage(getClass().getResource("\\images\\abstract-pastel-blue-white-background-design-34948659.jpg"));
            //Dimension dim=Toolkit.getDefaultToolkit().getScreenSize();
       
            Image j=im.getScaledInstance(this.getWidth(), this.getHeight(), Image.SCALE_REPLICATE);
            ImageIcon img=new ImageIcon(j);
            jLabel2.setIcon(img);
    }//GEN-LAST:event_formVetoableChange

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
